import type { InboxMessage } from '../api-types'
import type { FetchContext } from './fetch-wrapper'
import { fetchJson } from './fetch-wrapper'

/**
 * Inbox client — read, update, and delete inbox messages.
 *
 * Inbox messages are generated by scheduled tasks, heartbeat checks,
 * and agent notifications.
 *
 * Access via `client.inbox`.
 */
export interface InboxClient {
  /**
   * List inbox messages.
   * @param options - Filter options.
   * @param options.archived - If `true`, return archived messages instead of active ones.
   */
  list(options?: { archived?: boolean }): Promise<{ messages: InboxMessage[] }>

  /**
   * Get a single inbox message.
   * @param id - Message ID.
   * @throws {@link PandoraApiError} with status `404` if not found.
   */
  get(id: string): Promise<InboxMessage>

  /**
   * Update an inbox message (mark as read, archive/unarchive).
   * @param id - Message ID.
   * @param patch - Fields to update.
   * @returns The updated message.
   * @throws {@link PandoraApiError} with status `404` if not found.
   */
  update(id: string, patch: { read?: boolean; archived?: boolean }): Promise<InboxMessage>

  /**
   * Permanently delete an inbox message.
   * @param id - Message ID.
   * @throws {@link PandoraApiError} with status `404` if not found.
   */
  delete(id: string): Promise<{ deleted: string }>
}

/** @internal */
export function createInboxClient(ctx: FetchContext): InboxClient {
  return {
    list(options?: { archived?: boolean }): Promise<{ messages: InboxMessage[] }> {
      const query = options?.archived ? '?archived=true' : ''
      return fetchJson(ctx, `/api/inbox${query}`)
    },
    get(id: string): Promise<InboxMessage> {
      return fetchJson(ctx, `/api/inbox/${id}`)
    },
    update(id: string, patch: { read?: boolean; archived?: boolean }): Promise<InboxMessage> {
      return fetchJson(ctx, `/api/inbox/${id}`, {
        method: 'PATCH',
        body: JSON.stringify(patch),
      })
    },
    delete(id: string): Promise<{ deleted: string }> {
      return fetchJson(ctx, `/api/inbox/${id}`, { method: 'DELETE' })
    },
  }
}
