import type { Logger, PluginConfig } from './common'

export type { ConfigFieldDescriptor, EnvVarDescriptor, Logger, PluginConfig } from './common'

// ---------------------------------------------------------------------------
// Result types
// ---------------------------------------------------------------------------

/** A source referenced by the model. */
export interface Source {
  id: string
  sourceType: 'url' | 'document'
  title: string
  url?: string
  mimeType?: string
  filename?: string
}

/** A tool call made during generation. */
export interface ToolCall {
  toolCallId: string
  toolName: string
  args?: unknown
}

/** A tool execution result. */
export interface ToolResult {
  toolCallId: string
  toolName: string
  result: unknown
  isError?: boolean
}

/** A file generated by the model. */
export interface FileData {
  data: string | Uint8Array
  mimeType: string
}

/** A reasoning segment from the model. */
export interface Reasoning {
  id: string
  text: string
}

/** Token usage statistics. */
export interface Usage {
  inputTokens?: number
  outputTokens?: number
  totalTokens?: number
  reasoningTokens?: number
  cachedInputTokens?: number
}

// ---------------------------------------------------------------------------
// Message parts (what channels send to the gateway)
// ---------------------------------------------------------------------------

/** A text message part. */
export interface TextPart {
  type: 'text'
  text: string
}

/** A file/image message part. */
export interface FilePart {
  type: 'file'
  data: string | ArrayBuffer | Uint8Array
  mimeType: string
  filename?: string
}

/** Message part union — the parts a channel sends to the gateway. */
export type MessagePart = TextPart | FilePart

// ---------------------------------------------------------------------------
// Channel adapter (what channel packages export)
// ---------------------------------------------------------------------------

/** Webhook integration — platform sends HTTP requests. */
export interface ChannelWebhook {
  /** Verify request signature. Called before handle(). Return false to reject with 401. */
  verify(request: Request, env: Record<string, string | undefined>): Promise<boolean>
  handle(request: Request, runtime: ChannelGateway): Promise<Response>
}

/** Realtime integration — maintains a persistent connection. */
export interface ChannelRealtime {
  start(runtime: ChannelGateway): Promise<void>
  stop(): Promise<void>
}

/** A channel definition — the unit that channel packages export. */
export interface Channel {
  /** Unique channel identifier, e.g. 'telegram' */
  id: string
  /** Human-readable name, e.g. 'Telegram' */
  name: string
  /** Webhook mode — platform pushes HTTP requests */
  webhook?: ChannelWebhook
  /** Realtime mode — opens a persistent connection */
  realtime?: ChannelRealtime
}

/**
 * Factory function exported by channel packages.
 * Receives env vars and validated channel config.
 * Returns `null` when required env vars (e.g. bot token) are missing.
 */
export type ChannelFactory = (
  env: Record<string, string | undefined>,
  config: PluginConfig,
) => Channel | null

// ---------------------------------------------------------------------------
// Channel gateway (the interface core provides to channel adapters)
// ---------------------------------------------------------------------------

/** Pending tool approval info returned when finishReason is 'suspended'. */
export interface PendingToolApproval {
  toolCallId: string
  toolName: string
  args: unknown
}

/** Non-streaming result — all fields resolved. */
export interface GenerateResult {
  text: string
  sources: Source[]
  toolCalls: ToolCall[]
  toolResults: ToolResult[]
  files: FileData[]
  reasoning: Reasoning[]
  reasoningText?: string
  usage: Usage
  runId?: string
  pendingToolApproval?: PendingToolApproval
}

/** Streaming result — live text stream + promise-based fields. */
export interface StreamResult {
  textStream: ReadableStream<string>
  text: Promise<string>
  sources: Promise<Source[]>
  toolCalls: Promise<ToolCall[]>
  toolResults: Promise<ToolResult[]>
  files: Promise<FileData[]>
  reasoning: Promise<Reasoning[]>
  reasoningText: Promise<string | undefined>
  usage: Promise<Usage>
}

/** The gateway interface provided to channel adapters at runtime. */
export interface ChannelGateway {
  /** Send message and get full response (non-streaming). */
  generate(opts: {
    threadId: string
    parts: MessagePart[]
    /** Pass channelId + externalId to consume pending thread metadata. */
    channelId?: string
    externalId?: string
  }): Promise<GenerateResult>

  /** Send message and get streaming response. */
  stream(opts: {
    threadId: string
    parts: MessagePart[]
    /** Pass channelId + externalId to consume pending thread metadata. */
    channelId?: string
    externalId?: string
  }): Promise<StreamResult>

  /** Approve a pending tool call and resume generation. */
  approveToolCall(opts: { runId: string; toolCallId?: string }): Promise<GenerateResult>

  /** Decline a pending tool call and resume generation. */
  declineToolCall(opts: { runId: string; toolCallId?: string }): Promise<GenerateResult>

  /** Get or create an active thread for a channel+externalId pair. */
  resolveThread(channelId: string, externalId: string): Promise<string>

  /** Start a new conversation for a channel+externalId pair. */
  newThread(channelId: string, externalId: string): string

  /** Environment variables. */
  env: Record<string, string | undefined>

  /** Logger provided at runtime. */
  logger: Logger
}
